const DB_CONNECTION_TOKEN = 'DB_CONNECTION_TOKEN';
const MANGA_REPOSITORY_TOKEN = 'MANGA_REPOSITORY_TOKEN';
const CHAPTER_REPOSITORY_TOKEN = 'CHAPTER_REPOSITORY_TOKEN';

export {
  DB_CONNECTION_TOKEN,
  MANGA_REPOSITORY_TOKEN,
  CHAPTER_REPOSITORY_TOKEN,
};
