const DB_CONNECTION_TOKEN = 'DB_CONNECTION_TOKEN';
const MANGA_REPOSITORY_TOKEN = 'MANGA_REPOSITORY_TOKEN';
const CHAPTER_REPOSITORY_TOKEN = 'CHAPTER_REPOSITORY_TOKEN';
const USER_REPOSITORY_TOKEN = 'USER_REPOSITORY_TOKEN';
const ROLE_REPOSITORY_TOKEN = 'ROLE_REPOSITORY_TOKEN';
const USER_MANGA_CHAPTER_REPOSITORY_TOKEN =
  'USER_MANGA_CHAPTER_REPOSITORY_TOKEN';

export {
  DB_CONNECTION_TOKEN,
  MANGA_REPOSITORY_TOKEN,
  CHAPTER_REPOSITORY_TOKEN,
  USER_REPOSITORY_TOKEN,
  ROLE_REPOSITORY_TOKEN,
  USER_MANGA_CHAPTER_REPOSITORY_TOKEN,
};
